### PR TITLE
Fix issues in MB + ESB integration

### PR DESCRIPTION
**Pull request by indikasampath2000**
We have identified some issues in ESB + MB integration scenarios such as local transaction and failover.  This PR has set of fixes for each problem.

Resolves https://github.com/wso2/product-ei/issues/2208

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

### CODE REVIEW

**Comment by Nirothipan** [comment]
@indikasampath2000 Could you please explain the reason behind enabling andes client heartbeat by default ?
This prints the logs by default , is it the expected behavior
https://github.com/wso2/andes/blob/master/modules/andes-core/client/src/main/java/org/wso2/andes/client/protocol/HeartbeatDiagnostics.java#L98

Thanks

**Comment by a5anka** [comment]
AFAIU we have enabled heartbeat diagnostics (not the heartbeat feature) through "amqj.heartbeat.diagnostics". Do we need to enable diagnostics by default?

**Comment by indikasampath2000** [comment]
We can remove the `String value = System.getProperty("amqj.heartbeat.diagnostics", "true");` as it's just a metrics that printing details to System output.

**Comment by Nirothipan** [comment]
I've removed it in https://github.com/wso2/andes/pull/1020/files

**Pull request merged**
