### PR TITLE
Fixed MB-1862

### PR DESCRIPTION
**Pull request by sajinidesilva**

### CODE REVIEW

**Comment by ramith** [comment]
no description?

**Comment by ramith** [comment]
lets follow the best practice!

**Comment by sajinidesilva** [comment]
Fixed issue reported in https://wso2.org/jira/browse/MB-1862. The issue has occurred due to an exception throwing when creating channel at startup.

**Comment by a5anka** [comment]
It seems we have used a **AndesChannel that can be flow controlled** for UI tasks. Should we actually flow control the UI related tasks like restoring messages in DLC?

**Comment by a5anka** [comment]
Not good to merge PRs with unanswered questions. Feels neglected.

**Pull request merged**
