### PR TITLE
Modularize ProtocolType so that transports are pluggable to Andes core

### PR DESCRIPTION
**Pull request by akalankapagoda**
Allow transports to pluggable to Andes to remove some protocol specific logic from Andes core.

TODO's are added in places where protocol specific logic is tightly coupled with Andes core which should be separated before completing c5 integration.

### CODE REVIEW

**Comment by ramith** [comment]
@akalankapagoda what's the status of this PR? are we going to merge this?

**Comment by akalankapagoda** [comment]
I will merge this after merging other pulls available and resolving conflicts.

**Comment by akalankapagoda** [comment]
There is one specific protocol specific logic happening at https://github.com/wso2/andes/pull/565/files#diff-3c089a73dfbf91ccb07198d057542103R242.

This needs to be resolved when modularizing the metadata.

**Comment by ramith** [comment]
@akalankapagoda : lets do a code review.. :)

**Pull request merged**
